# This is a basic workflow to help you get started with Actions

name: PROD CI

# Controls when the workflow will run
on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Install
        run: npm install

      # Strip scope from package.json name
      - name: Unscope
        run: sed -i"" -e "s/@oslabs-beta\\/d3reactor/d3reactor/" package.json

      # Build package
      - name: Build
        run: npm run build

      - name: NPM Publish to github package repo
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          registry: https://registry.npmjs.org/
          # only run if published version number differs from the one in package.json
          check-version: true 